// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyBF6eWusHG2XvqOLhNwHqMOuSeeR10xQ_c',
//     appId: '1:503214777250:android:9d4ceee1cd5a7afcedc8fb',
//     messagingSenderId: '503214777250',
//     projectId: 'ayhamproject-758e8',
//     storageBucket: 'ayhamproject-758e8.firebasestorage.app',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyDIRb7PkmUSAlFzgaMvhvKmFpsv8v1bDHw',
//     appId: '1:503214777250:web:11fc089842cc6ba8edc8fb',
//     messagingSenderId: '503214777250',
//     projectId: 'ayhamproject-758e8',
//     authDomain: 'ayhamproject-758e8.firebaseapp.com',
//     storageBucket: 'ayhamproject-758e8.firebasestorage.app',
//     measurementId: 'G-2TMY4SF69Z',
//   );

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyDIRb7PkmUSAlFzgaMvhvKmFpsv8v1bDHw',
//     appId: '1:503214777250:web:11fc089842cc6ba8edc8fb',
//     messagingSenderId: '503214777250',
//     projectId: 'ayhamproject-758e8',
//     authDomain: 'ayhamproject-758e8.firebaseapp.com',
//     storageBucket: 'ayhamproject-758e8.firebasestorage.app',
//     measurementId: 'G-2TMY4SF69Z',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyBEoedO5qMeSMPqY5mjVFJGeZIOgqqPXpo',
//     appId: '1:503214777250:ios:6e77a0d4be386530edc8fb',
//     messagingSenderId: '503214777250',
//     projectId: 'ayhamproject-758e8',
//     storageBucket: 'ayhamproject-758e8.firebasestorage.app',
//     iosBundleId: 'com.example.nabtatcompany',
//   );

// }